name: Test code in notebooks

on:
  push:
    branches: [ master\+ipynb ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run test of notebooks manually' 

jobs:

  build-lnx:
    runs-on: ubuntu-latest
    container: openms/manylinux:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade jupyter
        if [ -f requirements.txt ]; then python3 -m pip install --upgrade -r requirements.txt; fi

    - name: Testing notebooks
      run: |
        for f in . do
          jupyter nbconvert --to notebook --inplace --execute $f
        done
